<?php

namespace OC\PlatformBundle\Entity;

/**
 * Advert1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Advert1Repository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertWithCategories(array $categories ){
        $ac = $this->createQueryBuilder('a');

        $ac->where($ac->expr()->in('a.author', $categories));

        return $ac
            ->getQuery()
            ->getResult()
            ;
    }

    public function getApplicationsWithAdvert($limit){
        $qb = $this->createQueryBuilder('a');

        $qb->setMaxResults($limit)
            ->orderBy('a.date', 'DESC')
            ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
